name: Build Server

on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/build-server.yml'
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/build-server.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@e32b06a3e831ff2fbc6f08cf35be2085e3918014 # v3.6.1
        with:
          ocaml-compiler: "5"
          dune-cache: true


      - run: |
          opam install frama-c
          opam exec -- dune build